import type { Offer } from './types';

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'offer-001',
    name: 'NextSales CRM Growth',
    description: 'Plano Growth do CRM NextSales com automações e agentes IA ilimitados.',
    offer_type: 'own',
    category: 'saas',
    journey_type: 'consultative',
    price: 197,
    price_recurrence: 'month',
    checkout_url: 'https://checkout.nextsales.com.br/growth',
    selling_arguments: 'CRM com IA nativa, automação de follow-up, agentes SDR/Closer. ROI médio em 60 dias.',
    priority: 'high',
    is_active: true,
    objections: [
      { id: 'obj-1', objection_text: 'Já uso outro CRM', suggested_reply: 'Nossa migração é assistida e gratuita. Em 2 horas você está operando.' },
      { id: 'obj-2', objection_text: 'Está caro', suggested_reply: 'Com 2 vendas fechadas pelos agentes IA você já paga o plano anual.' },
    ],
    agents_count: 4,
    sales_this_month: 12,
    revenue_this_month: 2364,
  },
  {
    id: 'offer-002',
    name: 'Curso Vendas B2B',
    description: 'Metodologia completa para vendas consultivas e prospecção B2B.',
    offer_type: 'affiliate',
    category: 'infoproduct',
    journey_type: 'immediate',
    price: 1200,
    price_recurrence: 'one_time',
    affiliate_platform: 'hotmart',
    affiliate_link: 'https://hotmart.com/produto/vendas-b2b?ref=abc123',
    commission_pct: 40,
    cookie_days: 30,
    sale_confirmation: 'webhook',
    priority: 'medium',
    is_active: true,
    objections: [],
    agents_count: 2,
    sales_this_month: 5,
    revenue_this_month: 1120,
  },
  {
    id: 'offer-003',
    name: 'Consultoria Comercial',
    description: 'Diagnóstico e reestruturação completa do processo comercial da empresa.',
    offer_type: 'own',
    category: 'consulting',
    journey_type: 'consultative',
    price: 5000,
    price_recurrence: 'one_time',
    checkout_url: 'https://calendly.com/nextsales/consultoria',
    selling_arguments: 'Diagnóstico em 48h, plano de ação personalizado, acompanhamento por 30 dias.',
    priority: 'high',
    is_active: true,
    objections: [
      { id: 'obj-3', objection_text: 'Não tenho orçamento agora', suggested_reply: 'Podemos parcelar em até 3x sem juros. O retorno costuma vir antes do fim do contrato.' },
    ],
    agents_count: 1,
    sales_this_month: 2,
    revenue_this_month: 10000,
  },
  {
    id: 'offer-004',
    name: 'Plataforma TechCorp',
    description: 'Plataforma de gestão para times de vendas enterprise.',
    offer_type: 'partner',
    category: 'saas',
    journey_type: 'scheduling',
    price: 297,
    price_recurrence: 'month',
    partner_name: 'TechCorp Solutions',
    partner_contact: 'parceiros@techcorp.com.br',
    commission_pct: 25,
    partner_commission_type: 'sale',
    partner_sla_hours: 48,
    priority: 'medium',
    is_active: true,
    objections: [],
    agents_count: 3,
    sales_this_month: 8,
    revenue_this_month: 5940,
  },
];
